import type { Metadata } from "next";
import MarketingNav from "@/components/marketing/MarketingNav";
import MarketingFooter from "@/components/marketing/MarketingFooter";

export const metadata: Metadata = {
  title: "Terms of Service | MansaMusaAI",
  description: "MansaMusaAI terms of service — your rights and responsibilities as a user.",
};

const sections = [
  { title: "Acceptance of terms", body: "By accessing or using MansaMusaAI, you agree to these Terms. If you don't agree, do not use the service." },
  { title: "Service description", body: "MansaMusaAI provides an AI Operating System for business, including AI chat, agent marketplace, analytics, CRM, and related features powered by Claude AI." },
  { title: "Acceptable use", body: "You must not use the service for illegal activities, generating harmful content, scraping, reverse engineering, or circumventing usage limits. You are responsible for all content generated through your account." },
  { title: "Subscriptions and billing", body: "Subscriptions are billed monthly in GBP via Stripe. You may cancel at any time; cancellation takes effect at the end of the current billing period. We offer a 7-day money-back guarantee on first-time paid subscriptions." },
  { title: "AI-generated content", body: "Content generated by AI agents is provided as-is. MansaMusaAI makes no warranty that AI outputs are accurate, complete, or suitable for your purpose. You must review all AI outputs before acting on them." },
  { title: "Intellectual property", body: "You retain ownership of content you provide. You grant us a licence to process it to deliver the service. MansaMusaAI's platform, branding, and technology remain our property." },
  { title: "Limitation of liability", body: "To the maximum extent permitted by law, MansaMusaAI shall not be liable for indirect, incidental, or consequential damages. Our total liability is limited to the amount you paid in the 12 months prior to the claim." },
  { title: "Termination", body: "We may suspend or terminate your account for violations of these Terms. You may delete your account at any time via the portal." },
  { title: "Governing law", body: "These Terms are governed by the laws of England and Wales. Disputes shall be subject to the exclusive jurisdiction of English courts." },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <MarketingNav />
      <main className="mx-auto max-w-3xl px-6 py-20">
        <p className="text-sm font-semibold uppercase tracking-widest text-brand-600 mb-3">Legal</p>
        <h1 className="text-4xl font-extrabold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: June 2026</p>
        <div className="space-y-8">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="text-lg font-bold text-gray-900 mb-2">{s.title}</h2>
              <p className="text-gray-600 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>
      </main>
      <MarketingFooter />
    </div>
  );
}
